name: CMake on multiple platforms

on:
  - push
  - pull_request
  - workflow_dispatch
    

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: clang

    steps:
      - uses: actions/checkout@v4
        name: Checkout ProjectHSI-Bot
        with:
          submodules: recursive

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      #- name: Install OpusFile for Linux
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: sudo apt-get install libopusfile 0 libopusfile-dev libxmp-dev

      #- name: Install OpusFile for MacOS
      #  if: ${{ matrix.os == 'macos-latest' }}
      #  run: brew install opusfile libxmp

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest --build-config ${{ matrix.build_type }}

      - name: Get Commit Hash
        id: gitcommitinfo
        shell: bash
        run: |
          echo "git-commit-hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "git-branch=$(git rev-parse --abbrev-ref HEAD)" >> "$GITHUB_OUTPUT"

      - name: Copy Build Artifacts For Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          copy ${{ github.workspace }}/build/ProjectHSI-Bot/Release/ProjectHSI-Bot.exe ${{ github.workspace }}/../output/ProjectHSI-Bot.exe
          copy ${{ github.workspace }}/build/third_party/SDL/Release/SDL2.dll ${{ github.workspace }}/../output/SDL2.dll

      - name: Copy Build Artifacts For MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          copy ${{ github.workspace }}/build/ProjectHSI-Bot/Release/ProjectHSI-Bot.exe ${{ github.workspace }}/../output/ProjectHSI-Bot.exe
          copy ${{ github.workspace }}/build/third_party/SDL/libSDL2-2.0.dylib ${{ github.workspace }}/../output/libSDL2-2.0.dylib

      - name: Copy Build Artifacts For Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          copy ${{ github.workspace }}/build/ProjectHSI-Bot/Release/ProjectHSI-Bot.exe ${{ github.workspace }}/../output/ProjectHSI-Bot.exe
          copy ${{ github.workspace }}/build/third_party/SDL/libSDL2-2.0.so ${{ github.workspace }}/../output/libSDL2-2.0.so

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ matrix.os }}-${{ matrix.c_compiler }}-${{ steps.gitcommitinfo.outputs.git-branch }}-${{ steps.gitcommitinfo.outputs.git-commit-hash }}
          path: |
            ${{ github.workspace }}/../output/
          if-no-files-found: error
          retention-days: 0